### ISSUE TITLE
DrawingBoard web sockets

### ISSUE THREAD

**Issue by marasanders** [ga-dc/websocket-arcade#10]
completeness 4
comfort 2.1

https://github.com/ga-wdi-exercises/websocket-arcade/issues/new

worked side by side with Julia N - 

don't think I could have done this without online help.  Would like to figure out how to hook up Jesse's code to web sockets - 

Did add the chat option from our lesson to the drawing and added a few color and cursor size changeability through chat - yellow - will change draw color to yellow ...

**Comment by nolds9** [comment]
👍
