### ISSUE TITLE
Battlesaurs!

### ISSUE THREAD

**Issue by alpha2262** [ga-dc/websocket-arcade#3]
Julia S, Chris, Adina, Michael H

https://github.com/jschultz21/battlesaurs/tree/master

Battleships concept game (which for the moment became more of a lightbrite-type game)
Questions: how to modify the information sent (or received) via the socket so a selection of a cell on Player A's screen shows an attack on Player B's screen with his ships included. Player A also needs to receive modified info if a hit is made.

**Comment by jshawl** [comment]
> Questions: how to modify the information sent (or received) via the socket so a selection of a cell on Player A's screen shows an attack on Player B's screen with his ships included. Player A also needs to receive modified info if a hit is made.

It may be easiest to send every move to every client, with a data structure like this:

``` js
var moves = {
  player1: [ a2,b3,c4],
  player2: [a1,a4,c8]
}
```

etc....

Then on every socket message, you construct the board depending on whether the client is either player1 or player 2. does that make sense?

happy to talk this out more in person. let me know!
