### ISSUE TITLE
JNajafi Websockets

### ISSUE THREAD

**Issue by JuliaNajafi** [ga-dc/websocket-arcade#9]
pictionary !
https://github.com/JuliaNajafi/websockectsLab

(disclaimer: found drawing board code online) 

completeness: 4/5
comfort level: 2/5 

couldnt figure out a way to somehow associate users with a specific color or username for the chat .. any suggestions for googling ? already looked into socket.join(room) and io.socket.clients() and couldnt get that working

**Comment by jshawl** [comment]
👍 awesome! 

When the user first opens a connection, assign them a color. Then, on each socket send, add their color to the line data - https://github.com/JuliaNajafi/websockectsLab/blob/master/index.js#L32
